#!/bin/sh -e

##########################################################################
#   Script description:
#       Select a sample for a given task ID in a job array
#       
#   History:
#   Date        Name        Modification
#   2021-05-21  Jason Bacon Begin
##########################################################################

samples="0ATAC-1 0ATAC-2 0ATAC-3 12ATAC-1 12ATAC-2 12ATAC-3 2ATAC-1 2ATAC-2 2ATAC-3 4ATAC-1 4ATAC-2 4ATAC-3 7ATAC-2 7ATAC-3"
my_sample=$(printf "$samples\n" | cut -d ' ' -f $SLURM_ARRAY_TASK_ID)
printf "Task $SLURM_ARRAY_TASK_ID running $my_sample on $(hostname)...\n"
